# Generated by Django 2.1.2 on 2018-10-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20181014_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.ManyToManyField(through='customers.PurchaseItem', to='customers.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.IntegerField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C')]),
        ),
    ]
