# Generated by Django 2.1.2 on 2018-11-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20181014_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('CAN_VIEW_CUSTOMER', 'Can View Customer'),)},
        ),
    ]
